### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by Filmz5** [PromtEngineer/localGPT#16]
receiving this error after install

AssertionError: Torch not compiled with CUDA enabled

**Comment by clovistx** [comment]
Both ingest.py and run_localGPT.py is forcing cuda device. Maybe if you change these device you could run.
I've tried on my Mac M1 to 'mps' but there is another error so i couldn't run the project yet.

**Comment by smithart** [comment]
Thanks, [zhuolisam](https://github.com/zhuolisam)! This solution worked for me.

**Comment by mindwellsolutions** [comment]
I'm assuming you are running this on Windows 10/11, since I only saw this error on that not my Ubuntu machine. This should install Cuda support for pytorch.

https://pub.towardsai.net/installing-pytorch-with-cuda-support-on-windows-10-a38b1134535e
