### ISSUE TITLE
Failed to import transformers.models.t5.modeling_t5

### ISSUE THREAD

**Issue by laurafbec** [PromtEngineer/localGPT#230]
Hi everyone
When trying to run the ingest.py I get the error:

```
PS C:\Users\xxxxx\source\repos\localGPT> python .\ingest.py
2023-07-15 19:34:34,994 - INFO - ingest.py:120 - Loading documents from C:\Users\xxxxx\source\repos\localGPT/SOURCE_DOCUMENTS
2023-07-15 19:34:38,280 - INFO - ingest.py:129 - Loaded 1 documents from C:\Users\xxxxx\source\repos\localGPT/SOURCE_DOCUMENTS
2023-07-15 19:34:38,280 - INFO - ingest.py:130 - Split into 72 chunks of text
2023-07-15 19:34:41,779 - INFO - SentenceTransformer.py:66 - Load pretrained SentenceTransformer: hkunlp/instructor-large
load INSTRUCTOR_Transformer
False

===================================BUG REPORT===================================
C:\Users\xxxxx\AppData\Roaming\Python\Python311\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes


  warn(msg)
================================================================================
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=121, Highest Compute Capability: 7.5.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary C:\Users\xxxxx\AppData\Roaming\Python\Python311\site-packages\bitsandbytes\libbitsandbytes_cuda121.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
Traceback (most recent call last):
  File "C:\Users\xxxxx\AppData\Roaming\Python\Python311\site-packages\transformers\utils\import_utils.py", line 1086, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxx\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\xxxxx\AppData\Roaming\Python\Python311\site-packages\transformers\models\t5\modeling_t5.py", line 36, in <module>
    from ...modeling_utils import PreTrainedModel
  File "C:\Users\xxxxx\AppData\Roaming\Python\Python311\site-packages\transformers\modeling_utils.py", line 85, in <module>
    from accelerate import __version__ as accelerate_version
  File "C:\Users\xxxxx\AppData\Roaming\Python\Python311\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "C:\Users\xxxxx\AppData\Roaming\Python\Python311\site-packages\accelerate\accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "C:\Users\xxxxx\AppData\Roaming\Python\Python311\site-packages\accelerate\checkpointing.py", line 24, in <module>
    from .utils import (
  File "C:\Users\xxxxx\AppData\Roaming\Python\Python311\site-packages\accelerate\utils\__init__.py", line 131, in <module>
    from .bnb import has_4bit_bnb_layers, load_and_quantize_model
  File "C:\Users\xxxxx\AppData\Roaming\Python\Python311\site-packages\accelerate\utils\bnb.py", line 42, in <module>
    import bitsandbytes as bnb
  File "C:\Users\xxxxx\AppData\Roaming\Python\Python311\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\Users\xxxxx\AppData\Roaming\Python\Python311\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\Users\xxxxx\AppData\Roaming\Python\Python311\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\Users\xxxxx\AppData\Roaming\Python\Python311\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\Users\xxxxx\AppData\Roaming\Python\Python311\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "C:\Users\xxxxx\AppData\Roaming\Python\Python311\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xxxxx\source\repos\localGPT\ingest.py", line 158, in <module>
    main()
  File "C:\Users\xxxxx\anaconda3\Lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxx\anaconda3\Lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxx\anaconda3\Lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxx\anaconda3\Lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxx\source\repos\localGPT\ingest.py", line 133, in main
    embeddings = HuggingFaceInstructEmbeddings(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxx\AppData\Roaming\Python\Python311\site-packages\langchain\embeddings\huggingface.py", line 137, in __init__
    self.client = INSTRUCTOR(
                  ^^^^^^^^^^^
  File "C:\Users\xxxxx\AppData\Roaming\Python\Python311\site-packages\sentence_transformers\SentenceTransformer.py", line 95, in __init__
    modules = self._load_sbert_model(model_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxx\AppData\Roaming\Python\Python311\site-packages\InstructorEmbedding\instructor.py", line 474, in _load_sbert_model
    module = module_class.load(os.path.join(model_path, module_config['path']))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxx\AppData\Roaming\Python\Python311\site-packages\InstructorEmbedding\instructor.py", line 306, in load
    return INSTRUCTOR_Transformer(model_name_or_path=input_path, **config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxx\AppData\Roaming\Python\Python311\site-packages\InstructorEmbedding\instructor.py", line 240, in __init__
    self._load_model(self.model_name_or_path, config, cache_dir, **model_args)
  File "C:\Users\xxxxx\AppData\Roaming\Python\Python311\site-packages\sentence_transformers\models\Transformer.py", line 47, in _load_model
    self._load_t5_model(model_name_or_path, config, cache_dir)
  File "C:\Users\xxxxx\AppData\Roaming\Python\Python311\site-packages\sentence_transformers\models\Transformer.py", line 53, in _load_t5_model
    from transformers import T5EncoderModel
  File "<frozen importlib._bootstrap>", line 1231, in _handle_fromlist
  File "C:\Users\xxxxx\AppData\Roaming\Python\Python311\site-packages\transformers\utils\import_utils.py", line 1077, in __getattr__
    value = getattr(module, name)
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxx\AppData\Roaming\Python\Python311\site-packages\transformers\utils\import_utils.py", line 1076, in __getattr__
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxx\AppData\Roaming\Python\Python311\site-packages\transformers\utils\import_utils.py", line 1088, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.t5.modeling_t5 because of the following error (look up to see its traceback):

        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
```
        
 
the nvidia-smi output is:

`nvidia-smi
Sat Jul 15 19:41:10 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 528.90       Driver Version: 528.90       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro T2000       WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   55C    P8     5W /  35W |    288MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+`

and the nvcc -V

`nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Jan__6_19:04:39_Pacific_Standard_Time_2023
Cuda compilation tools, release 12.0, V12.0.140
Build cuda_12.0.r12.0/compiler.32267302_0`

I dont know why CUDA setup failed. Thanks  in advance

**Comment by laurafbec** [comment]
The error has been solved by using `pip install git+https://github.com/Keith-Hon/bitsandbytes-windows.git`
Nevertheless, now I get memory errors when trying to use the GPU:
`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 86.00 MiB (GPU 0; 4.00 GiB total capacity; 3.38 GiB already allocated; 0 bytes free; 3.39 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`
I've tried to set the max_split_size_mb by using
`os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb:<size>"`, empty the cache `python -c 'import torch; torch.cuda.empty_cache()'` and modifying [memory ](https://github.com/PromtEngineer/localGPT/blob/925d63c66790d3787e58bbfd966797e03c2533f5/run_localGPT.py#L83C3-L83C3) with no luck.
Thanks in advance

**Comment by PromtEngineer** [comment]
Your GPU memory is not enough, I would recommend to you ggml models. Also to replace the instructor-embedding with huggingface embeddings. Will make this update soon.

**Comment by laurafbec** [comment]
Thanks @PromtEngineer. I've tried to improve the answers' time reponse by setting this [param](https://github.com/PromtEngineer/localGPT/blob/925d63c66790d3787e58bbfd966797e03c2533f5/run_localGPT.py#L83C3-L83C3) as I have 64GB RAM in my computer but I didn't notice a great improvement. Is it intended for that? thanks again

**Comment by aggiejiang** [comment]
Hello, I met the same problem when I used Llama model from huggingface in Linux. Did you solve this problem? Thanks

**Comment by laurafbec** [comment]
Hi @aggiejiang !! Sorry, I continue with the same problem. I've to try other embeddings and model to check it.
