### ISSUE TITLE
CUDA out of memory.

### ISSUE THREAD

**Issue by JesuisTong** [PromtEngineer/localGPT#285]
PC Hardware: 
- i7-9700kf
- Nvidia gtx 1660(6Gb)
- 16Gb memory

model used: 
- TheBloke/wizardLM-7B-GPTQ
- wizardLM-7B-GPTQ-4bit-128g.no-act.order.safetensors

env:
Running in windows10 WSL2.

error stack: 
2023-07-26 12:26:25,045 - INFO - run_localGPT.py:178 - Running on: cuda
2023-07-26 12:26:25,045 - INFO - run_localGPT.py:179 - Display Source Documents set to: False
2023-07-26 12:26:25,372 - INFO - SentenceTransformer.py:66 - Load pretrained SentenceTransformer: hkunlp/instructor-large
load INSTRUCTOR_Transformer
max_seq_length  512
2023-07-26 12:26:32,119 - INFO - __init__.py:88 - Running Chroma using direct local API.
2023-07-26 12:26:32,128 - WARNING - __init__.py:43 - Using embedded DuckDB with persistence: data will be stored in: /home/tongz/github/localGPT/DB
2023-07-26 12:26:32,141 - INFO - ctypes.py:22 - Successfully imported ClickHouse Connect C data optimizations
2023-07-26 12:26:32,153 - INFO - json_impl.py:45 - Using python library for writing JSON byte strings
2023-07-26 12:26:32,462 - INFO - duckdb.py:460 - loaded in 85 embeddings
2023-07-26 12:26:32,464 - INFO - duckdb.py:472 - loaded in 1 collections
2023-07-26 12:26:32,467 - INFO - duckdb.py:89 - collection with name langchain already exists, returning existing collection
2023-07-26 12:26:32,467 - INFO - run_localGPT.py:43 - Loading Model: TheBloke/wizardLM-7B-GPTQ, on: cuda
2023-07-26 12:26:32,467 - INFO - run_localGPT.py:44 - This action can take a few minutes!
2023-07-26 12:26:32,468 - INFO - run_localGPT.py:64 - Using AutoGPTQForCausalLM for quantized models
2023-07-26 12:26:32,975 - INFO - run_localGPT.py:71 - Tokenizer loaded
2023-07-26 12:26:34,335 - INFO - _base.py:727 - lm_head not been quantized, will be ignored when make_quant.
2023-07-26 12:26:39,547 - WARNING - modeling.py:1093 - The safetensors archive passed at /home/tongz/.cache/huggingface/hub/models--TheBloke--wizardLM-7B-GPTQ/snapshots/59de73dc34038cec634ce1c13ca6308235a14ba8/wizardLM-7B-GPTQ-4bit-128g.no-act.order.safetensors does not contain metadata. Make sure to save your model with the `save_pretrained` method. Defaulting to 'pt' metadata.
 2023-07-26 12:27:30,214 - WARNING - fused_llama_mlp.py:306 - skip module injection for FusedLlamaMLPForQuantizedModel not support integrate without triton yet.
Downloading (…)neration_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 132/132 [00:00<00:00, 882kB/s]
Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.
The model 'LlamaGPTQForCausalLM' is not supported for text-generation. Supported models are ['BartForCausalLM', 'BertLMHeadModel', 'BertGenerationDecoder', 'BigBirdForCausalLM', 'BigBirdPegasusForCausalLM', 'BioGptForCausalLM', 'BlenderbotForCausalLM', 'BlenderbotSmallForCausalLM', 'BloomForCausalLM', 'CamembertForCausalLM', 'CodeGenForCausalLM', 'CpmAntForCausalLM', 'CTRLLMHeadModel', 'Data2VecTextForCausalLM', 'ElectraForCausalLM', 'ErnieForCausalLM', 'FalconForCausalLM', 'GitForCausalLM', 'GPT2LMHeadModel', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTNeoForCausalLM', 'GPTNeoXForCausalLM', 'GPTNeoXJapaneseForCausalLM', 'GPTJForCausalLM', 'LlamaForCausalLM', 'MarianForCausalLM', 'MBartForCausalLM', 'MegaForCausalLM', 'MegatronBertForCausalLM', 'MusicgenForCausalLM', 'MvpForCausalLM', 'OpenLlamaForCausalLM', 'OpenAIGPTLMHeadModel', 'OPTForCausalLM', 'PegasusForCausalLM', 'PLBartForCausalLM', 'ProphetNetForCausalLM', 'QDQBertLMHeadModel', 'ReformerModelWithLMHead', 'RemBertForCausalLM', 'RobertaForCausalLM', 'RobertaPreLayerNormForCausalLM', 'RoCBertForCausalLM', 'RoFormerForCausalLM', 'RwkvForCausalLM', 'Speech2Text2ForCausalLM', 'TransfoXLLMHeadModel', 'TrOCRForCausalLM', 'XGLMForCausalLM', 'XLMWithLMHeadModel', 'XLMProphetNetForCausalLM', 'XLMRobertaForCausalLM', 'XLMRobertaXLForCausalLM', 'XLNetLMHeadModel', 'XmodForCausalLM'].
2023-07-26 12:27:31,195 - INFO - run_localGPT.py:125 - Local LLM Loaded

Enter a query: hello
Traceback (most recent call last):
  File "/home/tongz/github/localGPT/run_localGPT.py", line 258, in <module>
    main()
  File "/home/tongz/miniconda3/envs/localGPT/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/tongz/miniconda3/envs/localGPT/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/tongz/miniconda3/envs/localGPT/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tongz/miniconda3/envs/localGPT/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/tongz/github/localGPT/run_localGPT.py", line 236, in main
    res = qa(query)
  File "/home/tongz/miniconda3/envs/localGPT/lib/python3.10/site-packages/langchain/chains/base.py", line 140, in __call__
    raise e
  File "/home/tongz/miniconda3/envs/localGPT/lib/python3.10/site-packages/langchain/chains/base.py", line 134, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/home/tongz/miniconda3/envs/localGPT/lib/python3.10/site-packages/langchain/chains/retrieval_qa/base.py", line 119, in _call
    docs = self._get_docs(question)
  File "/home/tongz/miniconda3/envs/localGPT/lib/python3.10/site-packages/langchain/chains/retrieval_qa/base.py", line 181, in _get_docs
    return self.retriever.get_relevant_documents(question)
  File "/home/tongz/miniconda3/envs/localGPT/lib/python3.10/site-packages/langchain/vectorstores/base.py", line 376, in get_relevant_documents
    docs = self.vectorstore.similarity_search(query, **self.search_kwargs)
  File "/home/tongz/miniconda3/envs/localGPT/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 182, in similarity_search
    docs_and_scores = self.similarity_search_with_score(query, k, filter=filter)
  File "/home/tongz/miniconda3/envs/localGPT/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 229, in similarity_search_with_score
    query_embedding = self._embedding_function.embed_query(query)
  File "/home/tongz/miniconda3/envs/localGPT/lib/python3.10/site-packages/langchain/embeddings/huggingface.py", line 171, in embed_query
    embedding = self.client.encode([instruction_pair], **self.encode_kwargs)[0]
  File "/home/tongz/miniconda3/envs/localGPT/lib/python3.10/site-packages/InstructorEmbedding/instructor.py", line 521, in encode
    self.to(device)
  File "/home/tongz/miniconda3/envs/localGPT/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/home/tongz/miniconda3/envs/localGPT/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/tongz/miniconda3/envs/localGPT/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/tongz/miniconda3/envs/localGPT/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 6 more times]
  File "/home/tongz/miniconda3/envs/localGPT/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/home/tongz/miniconda3/envs/localGPT/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 6.00 GiB total capacity; 4.80 GiB already allocated; 0 bytes free; 5.03 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
2023-07-26 12:27:39,516 - INFO - duckdb.py:414 - Persisting DB to disk, putting it in the save folder: /home/tongz/github/localGPT/DB

**Comment by JesuisTong** [comment]
After i try to use model below with **cpu**, the problem solved.
- TheBloke/Llama-2-7B-Chat-GGML
- llama-2-7b-chat.ggmlv3.q4_0.bin

But there is another problem: `llama_tokenize: too many tokens` when i entered only `1`.

```sh
Enter a query: 1
llama_tokenize: too many tokens
Traceback (most recent call last): ....
ValueError: Requested tokens (3630) exceed context window of 2048
```

**Comment by JesuisTong** [comment]
Oops, if i just left the original file `constitution.pdf` in `SOURCE_DOCUMENTS`, then do `python ingest.py; python run_localGPT.py --device_type cpu`, it worked well(it is slow, but it worked).
My documents are all written by chinese, should i use a different tokenizer and a different llama model to response?

**Comment by nilvaes** [comment]
I have the same specs as you do, and I get the same error as: CUDA out of memory, which means our GPU VRAMs are not enough to run this model with GPU. There might be a way to use both GPU and CPU at the same time to lower the response time.

**Comment by zameergmail** [comment]
These are the crashes I am seeing

**Core Dumps**

`Enter a query: What is the beginning of the consitution?
Llama.generate: prefix-match hit
ggml_new_tensor_impl: not enough space in the scratch memory pool (needed 337076992, available 268435456)
Segmentation fault (core dumped)`

**Brutally slow response**

`$ python3 run_localGPT.py --device_type cuda
2023-07-29 02:55:52,181 - INFO - run_localGPT.py:178 - Running on: cuda
2023-07-29 02:55:52,181 - INFO - run_localGPT.py:179 - Display Source Documents set to: False
2023-07-29 02:55:52,517 - INFO - SentenceTransformer.py:66 - Load pretrained SentenceTransformer: hkunlp/instructor-large
load INSTRUCTOR_Transformer
max_seq_length  512
2023-07-29 02:55:56,132 - INFO - __init__.py:88 - Running Chroma using direct local API.
2023-07-29 02:55:56,138 - WARNING - __init__.py:43 - Using embedded DuckDB with persistence: data will be stored in: /data/home/challenger/localGPT/DB
2023-07-29 02:55:56,144 - INFO - ctypes.py:22 - Successfully imported ClickHouse Connect C data optimizations
2023-07-29 02:55:56,152 - INFO - json_impl.py:45 - Using python library for writing JSON byte strings
2023-07-29 02:55:56,215 - INFO - duckdb.py:460 - loaded in 360 embeddings
2023-07-29 02:55:56,218 - INFO - duckdb.py:472 - loaded in 1 collections
2023-07-29 02:55:56,219 - INFO - duckdb.py:89 - collection with name langchain already exists, returning existing collection
2023-07-29 02:55:56,219 - INFO - run_localGPT.py:43 - Loading Model: TheBloke/orca_mini_3B-GGML, on: cuda
2023-07-29 02:55:56,219 - INFO - run_localGPT.py:44 - This action can take a few minutes!
2023-07-29 02:55:56,219 - INFO - run_localGPT.py:48 - Using Llamacpp for GGML quantized models
llama.cpp: loading model from /home/challenger/.cache/huggingface/hub/models--TheBloke--orca_mini_3B-GGML/snapshots/423525dd58bf01fca2a7ef57b7f8f39d4a9366b8/orca-mini-3b.ggmlv3.q4_0.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 3200
llama_model_load_internal: n_mult     = 240
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 26
llama_model_load_internal: n_rot      = 100
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 8640
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 3B
llama_model_load_internal: ggml ctx size =    0.06 MB
llama_model_load_internal: mem required  = 2862.72 MB (+  682.00 MB per state)
llama_new_context_with_model: kv self size  =  650.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 | 

Enter a query: 1
-
llama_print_timings:        load time = 107628.01 ms
llama_print_timings:      sample time =    28.21 ms /    50 runs   (    0.56 ms per token,  1772.36 tokens per second)
llama_print_timings: prompt eval time = 107627.83 ms /  1007 tokens (  106.88 ms per token,     9.36 tokens per second)
llama_print_timings:        eval time =  8382.23 ms /    49 runs   (  171.07 ms per token,     5.85 tokens per second)
llama_print_timings:       total time = 116167.12 ms


> Question:
1

> Answer:
 The number of Representatives that each state is allowed to have is based on population, so it may fluctuate over time as populations change. For example, in 2020, California had 53 representatives while Wyoming only had one.

Enter a query: `

Can anyone share which model with which GPU works best/stable? I am using  Tesla P100

`# nvidia-smi 
Sat Jul 29 02:28:01 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla P100-PCIE-16GB           On  | 00000001:00:00.0 Off |                    0 |
| N/A   30C    P0              30W / 250W |   1598MiB / 16384MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      5861      C   python3                                    1596MiB |
+---------------------------------------------------------------------------------------+
root@dc-project-dobby:~# nvidia-smi 
Sat Jul 29 02:29:53 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla P100-PCIE-16GB           On  | 00000001:00:00.0 Off |                    0 |
| N/A   30C    P0              30W / 250W |   1598MiB / 16384MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      5861      C   python3                                    1596MiB |
+---------------------------------------------------------------------------------------+`
