### ISSUE TITLE
How to solve the problem with "torch.cuda.OutOfMemoryError"?

### ISSUE THREAD

**Issue by geer1895** [PromtEngineer/localGPT#293]
I could run **“run_localGPT.py”** without any **cuda.OutOfMemory errors**, but when I tried **“run_localGPT_API.py”**, it downloaded a new model and gave me a **cuda.OutOfMemoryError**. How can I fix this problem?
 I have a 3050Ti GPU, CUDA 11.8, and PyTorch 2.0.1. 
Thank you for your help.

**Comment by geer1895** [comment]
I checked the folder and found that the model **WizardLM-7B-uncensored-GPTQ**， which is used by the **“run_localGPT_API.py”** script, has a file named **WizardLM-7B-uncensored-GPTQ-4bit-128g.compat.no-act-order.safetensors.** However, the model **Llama-2-7B-Chat-GGML** only has a file named **llama-2-7b-chat.ggmlv3.q4_0.bin.** 
How can I solve this problem?

**Comment by PromtEngineer** [comment]
@geer1895 at the moment, you will need to change the model in `run_localGPT_API.py` manually. It needs some updates. You can find the gptq version of the llama model on huggingface.

**Comment by geer1895** [comment]
> @geer1895 at the moment, you will need to change the model in `run_localGPT_API.py` manually. It needs some updates. You can find the gptq version of the llama model on huggingface.

Thank you. I would have a try.

**Comment by geer1895** [comment]
For the question I raised earlier, I have found a solution that I hope can help you. 
You just need to copy the code from line 47 to line 61 of 'run_localGPT.py' to around line 97 of 'run_localGPT_API.py.' This will handle the missing .bin files, and you'll also need to add some additional library files for reference. With this, you'll be able to replace the model without having to download a new one.

I hope my modification can assist you in completing this project more effectively, enabling model replacement and dynamic updates between the two .py files when running on relatively low-level GPUs.
@PromtEngineer
